#!/bin/bash

#check if user do ok
if [ -f ~/.local/.ok ] ; then
   exit 0
fi 
   
time=300 #time to wait before starting 300 better
 
if [ -f "/usr/bin/yaourt" ] ; then

      sleep $time

#window for warning
            zenity --question --title="WARNING" --text="\nFull access to AUR detected!\nIf you would like to learn more about AUR features and risks (!) press OK and you will be redirected to the Wiki page.\n\nIf you already know what AUR is press Cancel" --cancel-label="Cancel" --ok-label="Ok" ;

      if [ $? == 1 ] ; then
         touch ~/.local/.ok
         exit 0
      fi  

#firefox open links in a tabs
      firefox https://wiki.manjaro.org/index.php/Arch_User_Repository https://wiki.archlinux.org/index.php/Arch_User_Repository https://wiki.archlinux.org/index.php/PKGBUILD https://wiki.archlinux.org/index.php/Makepkg

            zenity --question --text="Read this pages carefully before install AUR programs\nPress Yes to confirm that you have been informed about the risks of yaourt and AUR." ;
       
      if [ $? == 1 ] ; then
         exit 0
      fi  
      touch ~/.local/.ok
fi
